### ISSUE TITLE
Exception: Dockable 'clx-licensed-connections-tool' should not return 'null' for tabText()

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#104]
Hello,
I'm running into an issue when restoring the layout.
In this instance, the Dockable has not yet been registered, since it is added on the fly by an external plugin.
If I delete the layout.xml, then everything loads fine. I am assuming that it failed to load the Dockable since it is not registered yet. It is just an odd way for it to fail. And the dockable explicitly overrides the `getTabText()` and returns a string, so I am sure that it is not an issue with that.

Any help would be appreciated.
Thank you,
Trevor

```
ModernDocking.exception.DockingLayoutException
	at ModernDocking.persist.AppState.restore(AppState.java:182)
	at io.tlf.cip.tool.ui.MainWindow.lambda$restoreLayout$0(MainWindow.java:78)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.RuntimeException: Dockable 'clx-licensed-connections-tool' should not return 'null' for tabText()
	at ModernDocking.internal.DockingInternal.registerDockable(DockingInternal.java:62)
	at ModernDocking.Docking.registerDockable(Docking.java:108)
	at ModernDocking.internal.FailedDockable.<init>(FailedDockable.java:48)
	at ModernDocking.DockingState.getDockable(DockingState.java:376)
	at ModernDocking.DockingState.restoreTabbed(DockingState.java:323)
	at ModernDocking.DockingState.restoreState(DockingState.java:299)
	at ModernDocking.DockingState.restoreWindowLayout(DockingState.java:149)
	at ModernDocking.DockingState.restoreApplicationLayout(DockingState.java:110)
	at ModernDocking.persist.AppState.restore(AppState.java:170)
	... 14 more
```

Here is the layout XML
```
<?xml version="1.0" ?>
<app-layout>
<layout main-frame="true" location="730,400" size="1100,600" state="0">
<westToolbar>
</westToolbar>
<eastToolbar>
</eastToolbar>
<southToolbar>
</southToolbar>
</layout>
<undocked>
<simple persistentID="clx-licensed-connections-tool">
<properties></properties>
</simple>
<simple persistentID="Email">
<properties></properties>
</simple>
<simple persistentID="Message">
<properties></properties>
</simple>
<simple persistentID="Vendor Database">
<properties></properties>
</simple>
<simple persistentID="Discovery">
<properties></properties>
</simple>
<simple persistentID="DLR">
<properties></properties>
</simple>
<simple persistentID="Controller">
<properties></properties>
</simple>
<simple persistentID="Clock">
<properties></properties>
</simple>
<simple persistentID="Message Log">
<properties></properties>
</simple>
<simple persistentID="Status Code Database">
<properties></properties>
</simple>
<simple persistentID="EDS">
<properties></properties>
</simple>
<simple persistentID="Device Type Database">
<properties></properties>
</simple>
<simple persistentID="Factory Reset">
<properties></properties>
</simple>
<simple persistentID="Stratix">
<properties></properties>
</simple>
<simple persistentID="Tags">
<properties></properties>
</simple>
</undocked>
</app-layout>
```

ToolPanel.java
```
package io.tlf.cip.tool.ui.components;

import ModernDocking.Dockable;
import ModernDocking.DockableStyle;
import ModernDocking.Docking;
import io.tlf.cip.tool.ui.events.ToolDockedEvent;
import io.tlf.cip.tool.ui.events.ToolDockedListener;
import io.tlf.cip.tool.ui.events.ToolUndockedEvent;
import io.tlf.cip.tool.ui.events.ToolUndockedListener;

import javax.swing.*;

public class ToolPanel extends JPanel implements Dockable {

    private final String name;

    /**
     * Constructor for JFormDesigner, do not use
     */
    public ToolPanel() {
        this.name = getPersistentID();
    }

    public ToolPanel(String name) {
        this.name = name;
    }

    public void addToolUndockedListener(ToolUndockedListener listener) {
        listenerList.add(ToolUndockedListener.class, listener);
    }

    public void remoteToolUndockedListener(ToolUndockedListener listener) {
        listenerList.remove(ToolUndockedListener.class, listener);
    }

    private void fireToolUndocked() {
        Object[] listeners = listenerList.getListenerList();
        for (int i = 0; i < listeners.length; i += 2) {
            if (listeners[i] == ToolUndockedListener.class) {
                ((ToolUndockedListener) listeners[i + 1]).onToolUndocked(new ToolUndockedEvent(this, this));
            }
        }
    }

    public void addToolDockedListener(ToolDockedListener listener) {
        listenerList.add(ToolDockedListener.class, listener);
    }

    public void remoteToolDockedListener(ToolDockedListener listener) {
        listenerList.remove(ToolDockedListener.class, listener);
    }

    private void fireToolDocked() {
        Object[] listeners = listenerList.getListenerList();
        for (int i = 0; i < listeners.length; i += 2) {
            if (listeners[i] == ToolDockedListener.class) {
                ((ToolDockedListener) listeners[i + 1]).onToolDocked(new ToolDockedEvent(this, this));
            }
        }
    }

    public void updateTheme() {
        SwingUtilities.updateComponentTreeUI(this);
    }

    @Override
    public void onUndocked() {
        fireToolUndocked();
    }

    @Override
    public void onDocked() {
        fireToolDocked();
    }

    @Override
    public String getPersistentID() {
        return name;
    }

    @Override
    public int getType() {
        return 0;
    }

    @Override
    public String getTabText() {
        return name;
    }

    @Override
    public Icon getIcon() {
        return null;
    }

    @Override
    public boolean isFloatingAllowed() {
        return true;
    }

    @Override
    public boolean shouldLimitToRoot() {
        return false;
    }

    @Override
    public DockableStyle getStyle() {
        return DockableStyle.BOTH;
    }

    @Override
    public boolean canBeClosed() {
        return true;
    }

    @Override
    public boolean allowPinning() {
        return true;
    }

    @Override
    public boolean allowMinMax() {
        return false;
    }

    @Override
    public boolean hasMoreOptions() {
        return true;
    }
}
```

LicensedConnectionTool.java (I cut out the generated UI code to strip down and make it easier to read)
```
package io.tlf.cip.tool.ab.clx.license.ui;

import java.awt.*;
import java.awt.event.*;
import java.net.InetAddress;
import javax.swing.*;
import javax.swing.border.*;

import com.sun.security.auth.module.NTSystem;
import io.tlf.cip.tool.Main;
import io.tlf.cip.tool.ab.clx.license.net.ClxLicensedConnectionManager;
import io.tlf.cip.tool.net.cip.CipTcpClient;
import io.tlf.cip.tool.ui.components.*;
import lombok.Getter;
import net.miginfocom.swing.*;
import org.jdesktop.beansbinding.*;
import org.jdesktop.beansbinding.AutoBinding.UpdateStrategy;

/**
 * @author Trevor
 */
public class LicensedConnectionTool extends ToolPanel {

    @Getter
    private final Main main;

    @Getter
    private final ClxLicensedConnectionManager licensedConnectionManager;

    public LicensedConnectionTool(Main main) {
        super("clx-licensed-connections-tool");
        this.main = main;
        initComponents();
    }

    @Override
    public String getTabText() {
        return "ControlLogix Licensed Connections";
    }


    private void initComponents() {
        // JFormDesigner - Component initialization - DO NOT MODIFY  //GEN-BEGIN:initComponents  @formatter:off
        // Generated using JFormDesigner non-commercial license

        // JFormDesigner - End of component initialization  //GEN-END:initComponents  @formatter:on
    }

    // JFormDesigner - Variables declaration - DO NOT MODIFY  //GEN-BEGIN:variables  @formatter:off
    // Generated using JFormDesigner non-commercial license
  
    // JFormDesigner - End of variables declaration  //GEN-END:variables  @formatter:on
}
```

**Comment by andrewauclair** [comment]
which version are you using? I've fixed this at some point in a more recent update I believe. The issue here is that `FailedDockable.java` returned null for `getTabText()` and it now returns "Failed".

**Comment by tlf30** [comment]
I'm using version 0.8.0
```
    api 'io.github.andrewauclair.ModernDocking:ModernDocking:0.8.0'
    api 'io.github.andrewauclair.ModernDocking:ModernDockingUI:0.8.0'
```

**Comment by andrewauclair** [comment]
Thanks! I'll fix this and #102 and make a 0.8.1 for you. Main is a mess right now and I need to do a bunch of cleanup and testing for 0.9.0.

**Comment by tlf30** [comment]
Awesome, thank you so much!

**Comment by tlf30** [comment]
OK, so 0.8.1 did fix this. I did notice though, that an empty docking window can be created if the Dockable was unpinned, and when the app restarts if the Dockable is not registered. 

![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/a21b76a8-d6da-4f79-b353-f43db8f9c685)

**Comment by tlf30** [comment]
Perhaps I spoke too soon.
When I re-opened the app with the Dockable in the main window, it did this:
![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/c66e0feb-f98b-4c8c-b7cf-731f7b8e288e)

```
Exception in thread "AWT-EventQueue-0" ModernDocking.exception.DockableRegistrationFailureException: No root panel for window has been registered.
	at ModernDocking.internal.DockingComponentUtils.rootForWindow(DockingComponentUtils.java:98)
	at ModernDocking.internal.ActiveDockableHighlighter.lambda$new$0(ActiveDockableHighlighter.java:71)
	at java.desktop/java.awt.Toolkit$SelectiveAWTEventListener.eventDispatched(Toolkit.java:2193)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2084)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2084)
	at java.desktop/java.awt.Toolkit$ToolkitEventMulticaster.eventDispatched(Toolkit.java:2084)
	at java.desktop/java.awt.Toolkit.notifyAWTEventListeners(Toolkit.java:2041)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4901)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4572)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:191)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by andrewauclair** [comment]
Very strange issue. I wrapped the code to catch the `DockableRegisterationFailureException` in case there isn't a registered root for the window.

**Comment by andrewauclair** [comment]
Should be all set in 0.9.0.
