### ISSUE TITLE
Testing 0.10.0 beta

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#131]
Hello,
I just did a quick test with 0.10.0 beta.
It looks like everything is working except rendering the drop handles, both for reordering tabs and for dropping the panel.
No drop handles are rendered, and the background does not get grayed out while dragging. 

On launch I got this error:
```
Exception in thread "AWT-EventQueue-0" java.awt.IllegalComponentStateException: component must be showing on the screen to determine its location
	at java.desktop/java.awt.Component.getLocationOnScreen_NoTreeLock(Component.java:2113)
	at java.desktop/java.awt.Component.getLocationOnScreen(Component.java:2087)
	at ModernDocking.floating.DockingUtilsFrame.setSizeAndLocation(DockingUtilsFrame.java:230)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

**Comment by andrewauclair** [comment]
Nothing worse than a component must be showing exception.

New building is going now, should be fixed. I think I wasn't seeing it because of the way I have the demo apps configured. Everything happens in an `setVisible`. I should probably change that because it's not how I have it setup in my actual apps and it appears you have it setup differently too.

**Comment by tlf30** [comment]
Yeah, unfortunately I'm afraid that my setup is kinda complicated at this point. 
I am working on moving to a new setup, and right now I have two different abstraction layers (my new one and my old one), so everything is setup to support both right now.

I also dynamically register most of my dockables after creation as they are part of plugin jar files that get loaded late in the loading process. 

I call this first:
```
    private void initDocking() {
        // create the single Docking instance for the life of the program
        Docking.initialize(this);

        //Use tabs on top of dockable
        Settings.setAlwaysDisplayTabMode(true);

        // set the auto persist file
        // auto persist is off by default and we will leave it that way until we're done configuring the default layout
        // that way we're not persisting the default layout and overwriting the file before we load the file
        AppState.setPersistFile(new File("layout.xml"));
    }
```

Then I create the root docking panel

Then my tool handler is used to register all the "tools"

```
@Log4j2
public final class ToolHandler extends ArrayList<Tool> {

    private final PropertyChangeSupport changeSupport = new PropertyChangeSupport(this);

    private final Map<String, JMenuItem> toolMenuItems = new ConcurrentHashMap<>();

    @Getter
    private final MainWindow mainWindow;

    public ToolHandler(MainWindow mainWindow) {
        this.mainWindow = mainWindow;
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changeSupport.removePropertyChangeListener(listener);
    }

    public void register(Tool tool, String... menu) {
        if (!register(tool)) {
            return;
        }
        JMenu rootMenu = null;
        for (int i = 0; i < menu.length - 1; i++) {
            if (rootMenu == null) {
                boolean found = false;
                for (int m = 0; m < mainWindow.getMainMenuBar().getMenuCount(); m++) {
                    JMenu subMenu = mainWindow.getMainMenuBar().getMenu(m);
                    if (subMenu.getText().equals(menu[i])) {
                        rootMenu = subMenu;
                        found = true;
                    }
                }
                if (!found) {
                    rootMenu = new JMenu(menu[i]);
                    mainWindow.getMainMenuBar().add(rootMenu);
                }
            } else {
                boolean found = false;
                for (int m = 0; m < rootMenu.getItemCount(); m++) {
                    var subMenu = rootMenu.getItem(m);
                    if (subMenu.getText().equals(menu[i])) {
                        rootMenu = (JMenu) subMenu;
                        found = true;
                    }
                }
                if (!found) {
                    var subMenu = new JMenu(menu[i]);
                    rootMenu.add(subMenu);
                    rootMenu = subMenu;
                }
            }
        }

        JMenuItem toolMenuItem = new JMenuItem(menu[menu.length - 1]);
        toolMenuItem.addActionListener((event) -> {
            display(tool);
        });
        if (rootMenu != null) {
            rootMenu.add(toolMenuItem);
        } else {
            mainWindow.getMainMenuBar().add(toolMenuItem);
        }
        toolMenuItems.put(tool.getLicenseID(), toolMenuItem);
    }

    public void display(Tool tool) {
        Docking.display(tool.getPane());
    }

    @Override
    public boolean add(Tool tool) {
        return register(tool);
    }

    public boolean register(Tool tool) {

        //Verify license
        if (!Arrays.asList(mainWindow.getMain().getLicense().getTools()).contains(tool.getLicenseID())) {
            log.warn("Not licensed for tool: " + tool.getLicenseID() + " from class " + tool.getClass().getName());
            return false;
        }

        //Check duplicate persistent ID
        for (var t : this) {
            if (t.getLicenseID().equals(tool.getLicenseID())) {
                log.warn("Conflicting license ID: " + tool.getClass().getName() + " : " + tool.getClass().getName());
                return false;
            }
        }

        if (tool.getPane().getIcon() == null) {
            tool.getPane().setIcon(new ImageIcon(MainWindow.class.getResource("/logo.png")));
        }

        // register the dockable with the Docking framework in order to use it
        Docking.registerDockable(tool.getPane());

        super.add(tool);
        log.info("Registered tool " + tool.getName());
        return true;
    }

    public boolean remove(Tool tool) {
        if (!contains(tool)) {
            return false;
        }
        unregister(tool);

        return true;
    }

    public void unregister(Tool tool) {
        Docking.deregisterDockable(tool.getPane());

        super.remove(tool);
    }

    public Tool getTool(String licenseId) {
        for (var tool : this) {
            if (tool.getLicenseID().equals(licenseId)) {
                return tool;
            }
        }
        return null;
    }

    public Tool getToolByName(String name) {
        for (var tool : this) {
            if (tool.getName().equals(name)) {
                return tool;
            }
        }
        return null;
    }

    public void updateTheme() {
        for (var tool : this) {
            tool.getPane().updateTheme();
        }
    }

    /**
     * Dispose and shutdown all non-plugin tools
     */
    public void shutdown() {
        for (var tool : this) {
            if (tool.getPlugin() == null) {
                tool.getPane().dispose();
                tool.shutdown();
            }
        }
    }

    /**
     * Helper function for plugins to dispose and shutdown their tools
     *
     * @param plugin
     */
    public void shutdown(Plugin plugin) {
        for (var tool : this) {
            if (tool.getPlugin() == plugin) {
                tool.getPane().dispose();
                tool.shutdown();
            }
        }
    }
}
```
