### ISSUE TITLE
`RootDockingPanelAPI#createContents` crash

### ISSUE THREAD

**Issue by NebelNidas** [andrewauclair/ModernDocking#137]
The following is more or less what I'm doing:

```java
JFrame frame = new JFrame(windowTitle);
DockingAPI dockManager = new Docking(frame);
RootDockingPanelAPI workArea = new RootDockingPanel(dockManager, frame);
frame.getContentPane().setLayout(new BorderLayout());
frame.getContentPane().add(workArea, BorderLayout.CENTER);

DockableJPanel panel = new DockableJPanel(title, persistentId, dockManager);
dockManager.registerDockable(panel);
dockManager.dock(panel, frame, DockingRegion.NORTH);
```

At the last line it crashes:
```
Exception in thread "main" java.lang.IllegalArgumentException: cannot add to layout: constraint must be a string (or null)
        at java.desktop/java.awt.BorderLayout.addLayoutComponent(BorderLayout.java:431)
        at java.desktop/java.awt.Container.addImpl(Container.java:1156)
        at java.desktop/java.awt.Container.add(Container.java:1001)
        at ModernDocking.api.RootDockingPanelAPI.createContents(RootDockingPanelAPI.java:401)
        at ModernDocking.api.RootDockingPanelAPI.setPanel(RootDockingPanelAPI.java:224)
        at ModernDocking.api.RootDockingPanelAPI.dock(RootDockingPanelAPI.java:265)
        at ModernDocking.api.DockingAPI.dock(DockingAPI.java:356)
        at ModernDocking.api.DockingAPI.dock(DockingAPI.java:317)
```

Apparently it's illegal to pass a `GridBagConstraints` instance to `Container#add`?

**Comment by andrewauclair** [comment]
`RootDockingPanel` internally sets the layout to a `GridBagLayout`. You shouldn't set it yourself.

**Comment by NebelNidas** [comment]
Ah, that would explain it, thanks. Maybe try to catch the issue early and throw an appropriate error message?

**Comment by andrewauclair** [comment]
I don't think that's practical.

**Comment by andrewauclair** [comment]
Right. IMO you only set a layout on a `JPanel` that you have created directly, not a class that inherits from `JPanel`.
