### ISSUE TITLE
Floating Exception

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#184]
```
java.lang.ClassCastException: class javax.swing.JTabbedPane cannot be cast to class ModernDocking.internal.CustomTabbedPane (javax.swing.JTabbedPane is in module java.desktop of loader 'bootstrap'; ModernDocking.internal.CustomTabbedPane is in unnamed module of loader 'app')
        at ModernDocking.floating.FloatListener.updateFramePosition(FloatListener.java:209) 
        at ModernDocking.floating.FloatListener.dragMouseMoved(FloatListener.java:543) 
        at java.desktop/java.awt.dnd.DragSource.processDragMouseMoved(DragSource.java:789) 
        at java.desktop/java.awt.dnd.DragSourceContext.dragMouseMoved(DragSourceContext.java:469) 
        at java.desktop/sun.awt.dnd.SunDragSourceContextPeer$EventDispatcher.run(SunDragSourceContextPeer.java:487) 
        at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) 
        at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) 
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720) 
        at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714) 
        at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) 
        at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
        at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) 
        at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) 
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) 
        at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) 
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) 
        at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) 
        at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) 
        ```

**Comment by andrewauclair** [comment]
Looks like Modern Docking is picking up a different `JTabbedPane` from my app instead of the Modern Docking `CustomTabbedPane` it's looking for.
