### ISSUE TITLE
NoSuchMethod FlatSVGIcon.setColorFilter

### ISSUE THREAD

**Issue by nitanmarcel** [andrewauclair/ModernDocking#248]
No idea what I'm doing wrong. I added flatleaf extras to my gradle requirements and it still can't find that class

```
Exception in thread "AWT-EventQueue-0" java.lang.NoSuchMethodError: 'void com.formdev.flatlaf.extras.FlatSVGIcon.setColorFilter(com.formdev.flatlaf.extras.FlatSVGIcon$ColorFilter)'
	at ModernDocking.ext.ui.DockingUI.initialize(DockingUI.java:56)
	at ui.EditorWindow.initDefaultDocks(EditorWindow.kt:66)
	at ui.EditorWindow.<init>(EditorWindow.kt:32)
	at MainKt.main$lambda$2$lambda$0(Main.kt:15)
	at utils.WindowManager.showWindow(WindowManager.kt:16)
	at MainKt.main$lambda$2(Main.kt:15)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Process finished with exit code 130 (interrupted by signal 2:SIGINT)
```

```
dependencies {

    implementation("com.formdev:flatlaf:3.5.4")
    implementation("com.formdev:flatlaf-extras:3.5.4")
    implementation("com.formdev:flatlaf-intellij-themes:3.5.4")
    implementation("com.formdev:svgSalamander:1.1.4")
    implementation("dev.dirs:directories:26")
    implementation("io.codeworth:PanelMatic:0.9.9")
    implementation("com.alexandriasoftware.swing:jinputvalidator:0.9.0")
    implementation("io.github.andrewauclair:modern-docking-single-app:0.11.6")
    implementation("io.github.andrewauclair:modern-docking-ui:0.11.6")
    implementation("io.github.dj-raven:modal-dialog:2.1.0")
    implementation("org.apktool:apktool-lib:2.10.0")
    testImplementation(kotlin("test"))
}

```

**Comment by nitanmarcel** [comment]
This issue seems to only happen when using DockingUI.initialize. With Docking.initialize works fine

**Comment by andrewauclair** [comment]
Maybe try with the older flatlaf versions Modern Docking used for 0.11.6, which was 3.1.1, the classes used for the images has moved in more recent versions. Looks like I'm using 3.4 in main, and you are using 3.5. I'll see what happens if I build with the version you're using.

**Comment by nitanmarcel** [comment]
> Maybe try with the older flatlaf versions Modern Docking used for 0.11.6, which was 3.1.1, the classes used for the images has moved in more recent versions. Looks like I'm using 3.4 in main, and you are using 3.5. I'll see what happens if I build with the version you're using.

Yeah I already tried that too but the same thing happened

**Comment by andrewauclair** [comment]
Something is strange then. You should only need the flatlaf dependencies in your own build.gradle if you're going to use the IntelliJ themes. The svgSalamander dependency is no longer needed after flatlaf 3.2. I need to cleanup the Modern Docking demo dependencies more to reflect these.

**Comment by andrewauclair** [comment]
> > Maybe try with the older flatlaf versions Modern Docking used for 0.11.6, which was 3.1.1, the classes used for the images has moved in more recent versions. Looks like I'm using 3.4 in main, and you are using 3.5. I'll see what happens if I build with the version you're using.
> 
> Yeah I already tried that too but the same thing happened

Looks like I was wrong about which flatlaf version 0.11.6 uses. Try 3.2.5. I was just able to reproduce your issue using 0.11.6 and flatlaf 3.1.1 or 3.5.4. If I switch to 3.2.5, I'm able to run the app.

**Comment by nitanmarcel** [comment]
Yep that seems to be the issue. I can confirm that 3.2.5 works fine

**Comment by andrewauclair** [comment]
It looks like this shouldn't be an issue going forward with the latest versions of Modern Docking UI using Flatlaf 3.4 and 3.5. I don't think there's any easy way to prevent it from happening either, from what I can find online.
