### ISSUE TITLE
Can't Build Layout

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#53]
java.lang.NullPointerException: Cannot invoke "ModernDocking.layouts.DockingLayoutNode.replaceChild(ModernDocking.layouts.DockingLayoutNode, ModernDocking.layouts.DockingLayoutNode)" because "this.parent" is null
	at ModernDocking.layouts.DockingSimplePanelNode.dock(DockingSimplePanelNode.java:64)
	at ModernDocking.layouts.DockingLayoutBuilder.dock(DockingLayoutBuilder.java:44)

**Comment by andrewauclair** [comment]
Still broken when the builder uses tabbed panels.

**Comment by andrewauclair** [comment]
Even worse, the arguments to the dock functions in DockingLayoutBuilder are backwards when compared to the Docking.dock functions. Docking uses source, target and DockingLayoutBuilder uses target, source.
