### ISSUE TITLE
Feature: Tabs on top with no title bar

### ISSUE THREAD

**Issue by tlf30** [andrewauclair/ModernDocking#54]
Hello, 
I would like to request a feature (which will probably be complicated) to have the tabs on top, and use the tab to drag the panel. 
Something like how IDEA does their tabs:

![image](https://github.com/andrewauclair/ModernDocking/assets/10089434/cbac15ae-559b-46c7-8fbe-8633bc1d5a62)

Where the more options button would still be on the left, but the tab itself would be the draggable element and the close button would be on the tab. It would also be great if this functionality included reordering the tabs.

Thank you,
Trevor

**Comment by andrewauclair** [comment]
I like this idea. I also like the idea of showing some sort of dropdown, like IDEA does with the Project view.

![image](https://github.com/andrewauclair/ModernDocking/assets/2949516/d4d5898e-7e30-4f35-9aae-b38dbc2a5dd7)

I've seen some sample code of how to have tabs on top with close buttons for JTabbedPane. That part probably won't be too terrible. Making this a global option is probably easy, but I'd like this to tie into the Dockable type somehow. That way you could have Dockables that are of a certain "tab type" and they would only dock to like typed dockables.

**Comment by andrewauclair** [comment]
FlatLaf to the rescue! FlatLaf lets you set a trailing component for a JTabbedPane and it gets installed in the FlatTabbedPaneUI.

I'll have to build this into ModernDockingUI somehow to keep the FlatLaf dependency out of ModernDocking. Should be able to add the close button right to th etab, like the Oracle demos do. I'll work on a prototype feature I can check in.

![image](https://github.com/andrewauclair/ModernDocking/assets/2949516/4dc06aeb-0985-41bc-8227-823214e2a91c)

**Comment by tlf30** [comment]
That is cool. Thank you for looking into this, this is great. I really need to look at the UI components in FlatLaf more.

**Comment by tlf30** [comment]
I stumbled across some cood examples:

Tab with close button
https://github.com/aterai/java-swing-tips/tree/master/TabWithCloseButton

Trailing button on tabbed pane
https://github.com/aterai/java-swing-tips/tree/master/TabbedPaneWithButton

**Comment by andrewauclair** [comment]
Cool, thanks! Playing with this now and trying to figure out why I can click through their label but not mine.

**Comment by andrewauclair** [comment]
Figured that out. Had to use `SwingUtilities.invokeLater` when calling `setTabComponentAt`.

Aiming to add this as a real feature soon. I think the first version of it will be a global option for a tab style. Then I will be working on ways to set it per dockable.

**Comment by tlf30** [comment]
Nice, I think a global setting would be fine. I personally do not need to be able to mix styles.

**Comment by tlf30** [comment]
This is great thank you!

When removing a tab, and adding a new tab. An exception is thrown:
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 4 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at java.desktop/javax.swing.JTabbedPane.getTabComponentAt(JTabbedPane.java:2503)
	at ModernDocking.internal.DockedTabbedPanel.getTabForDockable(DockedTabbedPanel.java:376)
	at ModernDocking.internal.DockableWrapper.setParent(DockableWrapper.java:101)
	at ModernDocking.internal.DockedTabbedPanel.addPanel(DockedTabbedPanel.java:189)
	at ModernDocking.internal.DockedTabbedPanel.dock(DockedTabbedPanel.java:229)
	at ModernDocking.RootDockingPanel.dock(RootDockingPanel.java:224)
	at ModernDocking.Docking.dock(Docking.java:324)
	at ModernDocking.Docking.dock(Docking.java:281)
	at ModernDocking.Docking.dock(Docking.java:259)
	at io.tlf.cip.tool.ui.MainWindow.connectionWidget1OpenTool(MainWindow.java:173)
	at io.tlf.cip.tool.ui.MainWindow.lambda$initComponents$9(MainWindow.java:382)
	at io.tlf.cip.tool.ui.components.ConnectionWidget.fireOpenToolEvent(ConnectionWidget.java:146)
	at io.tlf.cip.tool.ui.components.ConnectionWidget.discoverButton(ConnectionWidget.java:156)
	at io.tlf.cip.tool.ui.components.ConnectionWidget.lambda$initComponents$1(ConnectionWidget.java:220)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2313)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:297)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6620)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6385)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4995)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4827)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:97)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```
The index increments for each time a tab is removed.

**Comment by andrewauclair** [comment]
Interesting. I didn't encounter that. How are you adding and removing? I'll give it a shot tonight.

**Comment by tlf30** [comment]
I'm adding them with the `Docking.dock(tool, this);` from within my main window. I'm closing them with the `x` button on the tab.

**Comment by andrewauclair** [comment]
Fixed an issue with the close button not using the proper index. It's not the same issue you're having. I was able to make your issue happen once I think and now I can't get it again. Possibly a timing issue.

**Comment by andrewauclair** [comment]
Not sure if the change I made fixed it or not. Not having any luck. I'll give it another shot tomorrow.

**Comment by andrewauclair** [comment]
Is it maybe already docked? Just made some test changes to manually call `Docking.dock` in the demo and I'm getting slightly different, but possibly related exceptions.

Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index -1 out-of-bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:440)
	at ModernDocking.internal.DockedTabbedPanel.getSelectedTabID(DockedTabbedPanel.java:339)
	at ModernDocking.layouts.DockingLayouts.tabbedPanelToNode(DockingLayouts.java:131)
	at ModernDocking.layouts.DockingLayouts.panelToNode(DockingLayouts.java:105)
	at ModernDocking.layouts.DockingLayouts.splitPanelToNode(DockingLayouts.java:127)
	at ModernDocking.layouts.DockingLayouts.panelToNode(DockingLayouts.java:102)
	at ModernDocking.layouts.DockingLayouts.splitPanelToNode(DockingLayouts.java:127)
	at ModernDocking.layouts.DockingLayouts.panelToNode(DockingLayouts.java:102)
	at ModernDocking.layouts.DockingLayouts.layoutFromRoot(DockingLayouts.java:85)
	at ModernDocking.DockingState.getWindowLayout(DockingState.java:69)
	at ModernDocking.DockingState.getApplicationLayout(DockingState.java:80)
	at ModernDocking.persist.AppState$1.actionPerformed(AppState.java:125)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:317)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:249)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:764)
	at java.desktop/java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:717)
	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:711)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:89)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:734)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:199)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

I'm noticing that `Docking.dock` does not undock the dockable if it is already docked somewhere. That's causing some interesting issues in the demo.

![image](https://github.com/andrewauclair/ModernDocking/assets/2949516/3b0b182d-ea14-429f-9c24-0ab09840f8a8)

**Comment by andrewauclair** [comment]
@tlf30 Sorry, this one was a bigger pain to figure out than I thought it would be! I believe I have fixed it now. Turned out to be a classic Java Swing issue where adding a component to a new parent removes it from the old parent. Doing so did not remove it from the `panels` list in `DockedTabbedPanel` but it did remove it from the JTabbedPane in there. This make the counts not match between them and they should always match.

**Comment by tlf30** [comment]
> Is it maybe already docked? Just made some test changes to manually call Docking.dock in the demo and I'm getting slightly different, but possibly related exceptions.

For my exception, the panel was not already docked. But I do simply use the `Docking.dock` to force an already docked panel to become visible, and have not seen any issues (as far as I know) doing so. 

>  I believe I have fixed it now. 
Awesome, thank you! 

I am loving the new tabs, the feel is amazing. It really changes how I am using my program. I have seen some strange top padding issues, but it is only on some dockables (not all) and only when that is the only dockable (1 tab) it just adds extra padding to the top (about 10 to 20 px, I have not measured yet). I have a feeling it is something in my code causing this and need to investigate. 

A cool feature would be to add the ability to set a custom context menu when a tab is right clicked. Perhaps a thought for the beginnings of an enhancement. We already have the custom context menu for the buttons on the right, with the new tab system I will be transitioning to using them for more global settings, and it would be cool to put the more tab specific settings as a context menu directly on the tab. If there were to ever be a custom right click tab context menu, having the option to move the docking/view settings to be visible on that menu and/or on the right hand menu would be very handy. That way the right hand menu could be setup for global settings and the right click tab menu could be for tab specific settings. Of course the would still be controlled per dockable and it would be up to the dockable to set them up that way. Just a thoughts.

Thanks for all the work on this!

**Comment by andrewauclair** [comment]
Closing this issue as I believe the feature is complete. We can open new issues for any bugs or enhancements to the tabs.
