### ISSUE TITLE
Index out of bounds issue

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#64]
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 1
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:361)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at ModernDocking.internal.DockedTabbedPanel.getSelectedTabID(DockedTabbedPanel.java:193)
	at ModernDocking.layouts.DockingLayouts.tabbedPanelToNode(DockingLayouts.java:115)
	at ModernDocking.layouts.DockingLayouts.panelToNode(DockingLayouts.java:89)
	at ModernDocking.layouts.DockingLayouts.splitPanelToNode(DockingLayouts.java:111)
	at ModernDocking.layouts.DockingLayouts.panelToNode(DockingLayouts.java:86)
	at ModernDocking.layouts.DockingLayouts.layoutFromRoot(DockingLayouts.java:69)
	at ModernDocking.DockingState.getWindowLayout(DockingState.java:64)
	at ModernDocking.DockingState.getApplicationLayout(DockingState.java:70)
	at ModernDocking.persist.AppState$1.actionPerformed(AppState.java:87)
	at java.desktop/javax.swing.Timer.fireActionPerformed(Timer.java:311)
	at java.desktop/javax.swing.Timer$DoPostEvent.run(Timer.java:243)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:771)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:722)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:716)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:741)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by andrewauclair** [comment]
Looks like I caused this while working on a different issue locally.
