### ISSUE TITLE
RootDockingPanel Always Uses Pinning Toolbars No Matter What pinningSupported is Set to

### ISSUE THREAD

**Issue by andrewauclair** [andrewauclair/ModernDocking#94]
RootDockingPanel needs to be fixed to only add the pinning toolbars requested by the application.

**Comment by andrewauclair** [comment]
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException: Cannot invoke "ModernDocking.internal.DockingPanel.removeChild(ModernDocking.internal.DockingPanel)" because "this.parent" is null
	at ModernDocking.internal.DockedSimplePanel.undock(DockedSimplePanel.java:138)
	at ModernDocking.Docking.undock(Docking.java:559)
	at ModernDocking.internal.DockingComponentUtils.undockComponents(DockingComponentUtils.java:51)
	at ModernDocking.internal.DockingComponentUtils.undockComponents(DockingComponentUtils.java:54)
	at ModernDocking.internal.DockingComponentUtils.undockComponents(DockingComponentUtils.java:54)
	at ModernDocking.internal.DockingComponentUtils.undockComponents(DockingComponentUtils.java:54)
	at ModernDocking.internal.DockingComponentUtils.undockComponents(DockingComponentUtils.java:54)
	at ModernDocking.DockingState.restoreApplicationLayout(DockingState.java:99)
	at ModernDocking.persist.AppState.restore(AppState.java:176)
	at basic.MainFrame.lambda$call$8(MainFrame.java:329)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

Looks like this is a possible issue when upgrading. If dockables were pinned and they're reloaded into a frame that no longer supports pinning. Need to investigate.
